include: package:lint/analysis_options.yaml

linter:
  rules:
    - use_key_in_widget_constructors
    - avoid_relative_lib_imports
    - prefer_relative_imports
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
